config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'quizzes#index'
  resources :quizzes do
    resources :comments, only: [:new, :create]
    resources :quiz_lists, only: [:new, :create]
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :quiz
  validates :content, presence: true
end

app/models/form/base.rb
class Form::Base
  include ActiveModel::Model
  include ActiveModel::Callbacks
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks
end

app/models/form/quiz_list_collection.rb
class Form::QuizListCollection < Form::Base
  FORM_COUNT = 10
  attr_accessor :quiz_lists, :quiz_id

  def initialize(attributes = {})
    binding.pry
    super attributes
    self.quiz_lists = FORM_COUNT.times.map { QuizList.new() } unless self.quiz_lists.present?
  end

  def quiz_lists_attributes=(attributes)
    self.quiz_lists = attributes.map { |_, v| QuizList.new(v) }
  end

  def save
    quiz_list.transaction do
      self.quiz_lists.map do |quiz_list|
        if quiz_list.question != nil || quiz_list.answer != nil
          quiz_list.save
        end
      end
    end
      return true
    rescue => e
      return false
  end
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user
  has_many :quiz_lists, dependent: :destroy
  has_many :comments, dependent: :destroy
  with_options presence: true do
    validates :title
    validates :explanation
  end
end

app/models/quiz_list.rb
class QuizList < ApplicationRecord
  belongs_to :quiz
  with_options presence: true do
    validates :question
    validates :answer
  end
  
  def attributes
    { question: nil, answer: nil }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  has_one_attached :image
  has_many :quizzes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameter, if: :devise_controller?

  private

  def configure_permitted_parameter
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :password, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @quiz = Quiz.find(params[:quiz_id])
    @comment = @quiz.comments.new(comment_params)
    render json: { comment: @comment } if @comment.save
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/quiz_lists_controller.rb
class QuizListsController < ApplicationController
  def new
    @quiz = Quiz.find(params[:quiz_id])
    @form = Form::QuizListCollection.new
  end

  def create
    @quiz = Quiz.find(params[:quiz_id])
    @form = Form::QuizListCollection.new(quiz_list_collection_params)
    if @form.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def quiz_list_collection_params
    params.require(:form_quiz_list_collection).permit(quiz_lists_attributes: [:question, :answer])
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :identify_user, only: [:edit, :destroy]
  before_action :find_quiz, only: [:show, :edit, :update, :destroy]

  def index
    @quizzes = Quiz.includes(:user).order('created_at DESC')
  end

  def new
    @quiz = Quiz.new
  end
  # def new
  #   @quiz_management = QuizManagement.new
  # end

  def create
    @quiz = Quiz.new(quiz_params)
    if @quiz.save
      redirect_to new_quiz_quiz_list_path(@quiz)
    else
      render :new
    end
  end
  # def create
  #   build_quiz_management
  #   if @quiz_management.valid?
  #     @quiz_management.save
  #     redirect_to root_path
  #   else
  #     render :new
  #   end
  # end

  def show
    @comment = Comment.new
    @comments = @quiz.comments.includes(:user).order('created_at DESC')
    @quiz_lists = @quiz_lists.shuffle
    @json_quiz = @quiz_lists.to_json
    @json_info = [current_user.nickname, @quiz.id].to_json if user_signed_in?
  end

  # def edit
  #   @quiz_sets = @quiz_lists
  #   @quiz_management = QuizManagement.new
  # end

  # def update
  #   build_quiz_management
  #   if @quiz_management.valid?
  #     @quiz_management.update(@quiz)
  #     redirect_to root_path
  #   else
  #     render :edit
  #   end
  # end

  def destroy
    @quiz.destroy
    redirect_to root_path
  end

  private

  # def build_quiz_management
  #   @quiz_sets = []
  #   create_quiz_sets
  #   @quiz_management = QuizManagement.new(quiz_params)
  # end

  # def create_quiz_sets
  #   i = 0
  #   while params[:quiz_management][i.to_s]
  #     quiz_set = params[:quiz_management][i.to_s].permit(:question, :answer).to_h
  #     @quiz_sets << quiz_set if !quiz_set[:question].blank? && !quiz_set[:answer].blank?
  #     i += 1
  #   end
  # end

  def quiz_params
    params.require(:quiz).permit(:title, :explanation).merge(user_id: current_user.id)
  end

  # def quiz_params
  #   params.require(:quiz_management).permit(:title, :explanation).merge(quiz_sets: @quiz_sets, user_id: current_user.id)
  # end

  def find_quiz
    @quiz = Quiz.find(params[:id])
    @quiz_lists = @quiz.quiz_lists
  end

  def identify_user
    redirect_to root_path if current_user != Quiz.find(params[:id]).user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @quizzes = @user.quizzes
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    image = @user.image
    params[:user][:image] = image if params[:user][:image].nil?

    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:nickname, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_image_link(user, image_size)
    html = ""
    if user.image.attached?
      html = link_to image_tag(user.image.variant(resize_to_fill: [image_size, image_size])), user_path(user)
    end
    return raw(html)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/quiz_lists_helper.rb
module QuizListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YourTyping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header"%>
    <%= yield %>
  </body>
</html>

app/views/quiz_lists/new.html.erb
<div class="wrapper">
  <%= form_with model: [@quiz, @form], url: quiz_quiz_lists_path do |form| %>
    <table class="#">
      <thead>
        <tr>
          <th>問題文</th>
          <th>解答</th>
        </tr>
      </thead>
      <tbody class="#">
        <%= form.fields_for :quiz_lists do |f| %>
          <tr class="#">
            <td class="#">
              <%= f.text_area :question, class: '#' %>
            </td>
            <td>
              <%= f.text_field :answer, class: '#' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="#">
      <%= form.submit '一括登録', class: '#' %>
    </div>
  <% end %>
</div>

app/views/quizzes/edit.html.erb
<div class="wrapper">
  <%= form_with model: @quiz_management, url: quiz_path(@quiz), method: :patch, local: true do |f| %>
    <div class="quiz-form">
      <div class="error-message">
        <%= render "shared/error_messages", resource: f.object %>
      </div>
      <p class="title">クイズ編集</p>
      <ul class="explanation-list">
        <li>・問題と答えを両方セットで記入してください</li>
        <li>・最低3セットが必要になります</li>
        <li>・問題数を編集前より増やしたいときは下のボタンを押してください</li>
      </ul>
      <div class="quiz-set">
        <div class="quiz-input">
          <%= f.label :title, "クイズのタイトル", class: "quiz-label" %>
          <%= f.text_field :title, class: "quiz-field", value: @quiz.title, placeholder: "例) 英単語クイズ", autofocus: true %>
        </div>
        <div class="quiz-input">
          <%= f.label :explanation, "クイズの説明", class: "quiz-label" %>
          <%= f.text_area :explanation, class: "quiz-area", value: @quiz.explanation, placeholder: "例) 日本語を英語に直しましょう" %>
        </div>
      </div>
      <div id="all_quiz">
        <% i = 0 %>
        <% while i < @quiz_lists.length %>
          <div class="quiz-set">
            <div class="quiz-input">
              <%= f.label :question, "問題", class: "quiz-label" %>
              <%= f.text_area :question, index: i, class: "quiz-area", value: @quiz_lists[i].question, placeholder: "例) 英語" %>
            </div>
            <div class="quiz-input">
              <%= f.label :answer, "答え", class: "quiz-label" %>
              <%= f.text_field :answer, index: i, class: "quiz-field", value: @quiz_lists[i].answer, placeholder: "例) english" %>
            </div>
          </div>
          <% i += 1 %>
        <% end %>
      </div>
      <div class="buttons", id="buttons">
        <div class="increase-btn", id="increase">
          問題数を増やす
        </div>
        <div class="submit-btn">
          <%= f.submit "クイズ編集" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/quizzes/index.html.erb
<div class ="wrapper">
  <% if user_signed_in? %>
    <div class="create-btn">
      <%= link_to "クイズを作る", new_quiz_path %>
    </div>
  <% end %>
  <% if @quizzes != [] %>
    <div class="quiz-index">
      <% @quizzes.each do |quiz| %>
        <div class="quiz">
          <div class="quiz-header">
            <div class="index-quiz-title">
              <%= quiz.title %>
            </div>
            <div class="quiz-user">
              作成者:
              <%= user_image_link(quiz.user, 20) %> 
              <%= link_to "#{quiz.user.nickname}", user_path(quiz.user) %>
            </div>
          </div>
          <div class="index-quiz-explanation">
            <%= quiz.explanation %>
          </div>
          <div class="quiz-links">
            <div class="play-quiz">
              <%= link_to "Play", quiz_path(quiz) %>
            </div>
            <% if user_signed_in? && quiz.user == current_user %>
              <div class="edit-quiz">
                <%= link_to 'クイズの編集', edit_quiz_path(quiz) %>
                <%= link_to 'クイズの削除', quiz_path(quiz), method: :delete %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/quizzes/new.html.erb
<div class="wrapper">
  <%= form_with model: @quiz, url: quizzes_path, local: true do |f| %>
    <div class="quiz-form">
      <div class="error-message">
        <%= render "shared/error_messages", resource: f.object %>
      </div>
      <p class="title">クイズ新規登録</p>
      <div class="quiz">
        <div class="quiz-input">
          <%= f.label :title, "クイズのタイトル", class: "quiz-label" %>
          <%= f.text_field :title, class: "quiz-field", placeholder: "例) 英単語クイズ", autofocus: true %>
        </div>
        <div class="quiz-input">
          <%= f.label :explanation, "クイズの説明", class: "quiz-label" %>
          <%= f.text_area :explanation, class: "quiz-area", placeholder: "例) 日本語を英語に直しましょう" %>
        </div>
      </div>
      <div class="submit-btn">
        <%= f.submit "クイズ概要登録" %>
      </div>
    </div>
  <% end %>
</div>

app/views/quizzes/show.html.erb
<div class="wrapper">
  <div class="quiz-wrapper">
    <input id="json_quiz" type="hidden" value=<%= @json_quiz %>>
    <div class="quiz-title">
      <%= @quiz.title %>
    </div>
    <div class="quiz-explanation">
      <%= @quiz.explanation %>
    </div>
    <div class="quiz-main">
      <div class="question-area" id="question_area">
      </div>
      <div class="answer-area" id="answer_area">
        <input id="answer">
      </div>
    </div>
    <div class="top-link">
      <%= link_to 'トップページに戻る', root_path %>
    </div>
  </div>
  <div class="comment-wrapper">
    <% if user_signed_in? %>
      <input id="json_info" type="hidden" value=<%= @json_info %>>
      <%= form_with model: [@quiz, @comment], class: "comment-form", local: true, id: "new_comment" do |f| %>
        <div class="comment-field">
          <div class="error-message">
            <%= render "shared/error_messages", resource: f.object %>
          </div>
          <%= f.label :content, "コメント" %><br>
          <%= f.text_area :content %>
        </div>
        <div class="comment-submit">
          <%= f.submit "コメント記入", id: "submit_btn" %>
        </div>
      <% end %>
    <% end %>  
    <div class="comment-list" id="comment_list">
      <% if @comments != [] %>
        <% @comments.each do |comment| %>
          <% if comment.content != "" %>
            <div class="comment">
              <%= user_image_link(comment.user, 17) %>
              <%= link_to comment.user.nickname, user_path(comment.user) %>
              <div class="comment-content">
                <%= comment.content %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>   
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Your Quiz", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to current_user.nickname, user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/edit.html.erb
<div class="wrapper">
  <%= form_with model: @user, url: user_path, method: :patch, local: true do |f| %>
    <div class="form">
      <div class="error-message">
        <%= render "shared/error_messages", resource: f.object %>
      </div>
      <p class="title">ユーザー情報更新</p>
      <div class="user-input">
        <%= f.label :nickname, "ニックネーム", class: "user-label" %>
        <%= f.text_field :nickname, class: "user-field", placeholder:"例) クイズ一郎", autofocus: true, value: @user.nickname %>
      </div>
      <div class="user-input">
        <%= f.label :image, "ユーザーアイコン", class: "user-label" %>
        <%= f.file_field :image %>
      </div>
      <div class="submit-btn">
        <%= f.submit "更新" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class ="wrapper">
  <div class="user-page-title">
  <h1><%= user_image_link(@user, 40) %> <%= "#{@user.nickname}さんのページ" %></h1>
  <% if @user = current_user %>
    <%= link_to "ユーザー情報を編集する", edit_user_path, class: "user-link" %>
  <% end %>
  </div>
  <% if @quizzes != [] %>
    <div class="quiz-index">
      <% @quizzes.each do |quiz| %>
        <div class="quiz">
          <div class="quiz-header">
            <div class="index-quiz-title">
              <%= quiz.title %>
            </div>
          </div>
          <div class="index-quiz-explanation">
            <%= quiz.explanation %>
          </div>
          <div class="quiz-links">
            <div class="play-quiz">
              <%= link_to "Play", quiz_path(quiz) %>
            </div>
            <% if user_signed_in? && @user == current_user %>
              <div class="edit-quiz">
                <%= link_to 'クイズを編集する', edit_quiz_path(quiz) %>
                <%= link_to 'クイズを削除する', quiz_path(quiz), method: :delete %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>